services:
  vendorverse-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendorverse_app
    restart: always
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
